server:
  port: 9201

spring:
  application:
    name: gateway-worldwide
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes:
        - id: account-admin
          uri: lb://account-admin
          predicates:
            - Path=/account-admin/**
          filters:
            - StripPrefix=1
        - id: mall-product
          uri: lb://mall-product
          predicates:
            - Path=/mall-product/**
          filters:
            - StripPrefix=1
