server:
  port: 8761

spring:
  application:
    name: eureka-worldwide
ribbon:
  eureka:
    enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
