server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#    healthcheck:
#      enabled: true
    registry-fetch-interval-seconds: 5

mybatis-plus:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
  type-enums-package: com.ethan.worldwide.mall.product.infra.dao.enums
spring:
  application:
    name: mall-product
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://rm-bp1d1n5p12wh85975ao.mysql.rds.aliyuncs.com:3306/one_mall?serverTimezone=Asia/Shanghai
#    username: mall
#    password: "@Ahui940722"

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://rm-bp1d1n5p12wh85975.mysql.rds.aliyuncs.com:3306/one_mall?serverTimezone=Asia/Shanghai
#    username: mall
#    password: "@Ahui940722"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://100.85.113.163:3306/one_mall?serverTimezone=Asia/Shanghai
    username: root
    password: HW@Imc&369!

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/one_mall?serverTimezone=Asia/Shanghai
#    username: root
#    password: ahui940722
    hikari:
      minimum-idle: 5 # 池中最小空闲连接数量，默认值10
      idle-timeout: 600000 # 空闲时间
      maximum-pool-size: 10 # 池中的最大连接数（包括空闲和正在使用的连接）
      auto-commit: true # 是否自动提交池中返回的连接
      pool-name: myHikariCP # 连接池的名字
      max-lifetime: 1800000 # 连接池中连接的最大生命周期
      connection-timeout: 30000 # 连接超时时间。默认30s
      connection-test-query: select 1